from typing import Protocol

class IMagneticSensor(Protocol):
    def get_x_y_z(self) -> tuple[float,float,float]:
        ...
    def get_orientation(self) -> int:
        ...
    @classmethod
    def get_NSEW_string(cls,degrees:int) -> str:
        ...
    def get_data(self)->tuple[int,tuple[int,int],str]:
        """Returns a tuple of (Angle,(X,Y),"NESW string")"""
        ...